services:
  ah-shop:
    container_name: ah-shop
    build:
      context: ..
      dockerfile: Raft.Shop/Dockerfile
    image: ah-shop
    ports:
      - 344:8080
    profiles:
      - server-5
    environment:
      - RAFT_GATEWAY_URL=http://ah-gateway:8080

  ah-gateway:
    container_name: ah-gateway
    build:
      context: ..
      dockerfile: Raft.GateWay/Dockerfile
    image: ah-gateway
    ports:
      - 345:8080
    environment:
      - NODE_ADDRESSES=http://ah-node-1:8080,http://ah-node-2:8080,http://144.17.92.14:349
      - NODE_IDS=ah-node-1,ah-node-2,ah-node-3
    profiles:
      - server-5

  ah-node-1:
    container_name: ah-node-1
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    image: ah-node
    environment:
      - NODE_ID=ah-node-1
      - PEER_ADDRESSES=http://ah-node-2:8080,http://144.17.92.14:348
      - PEER_IDS=ah-node-2,ah-node-3
    ports:
      - 346:8080
    profiles:
      - server-5

  ah-node-2:
    container_name: ah-node-2
    environment:
      - NODE_ID=ah-node-2
      - PEER_ADDRESSES=http://ah-node-1:8080,http://144.17.92.14:348
      - PEER_IDS=ah-node-2,ah-node-3
    image: ah-node
    ports:
      - 347:8080
    profiles:
      - server-5

  ah-node-3:
    container_name: ah-node-3
    environment:
      - NODE_ID=ah-node-3
      - PEER_ADDRESSES=http://144.17.92.15:346,http://144.17.92.15:347
      - PEER_IDS=ah-node-1,ah-node-2
    build:
      context: ..
      dockerfile: Raft.Node/Dockerfile
    image: ah-node
    ports:
      - 348:8080
    profiles:
      - server-4

networks:
  default:
    name: ah-raft-network
