name: Raftr
run-name: ${{ github.actor }} is deploying 🚀
on: [push]

jobs:
  test:
    runs-on: [self-hosted, server-5]
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Test
          run: |
            dotnet test Raft.Tests 

  deploy-server-5:
      runs-on: [self-hosted, server-5]
      needs: test
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          cd ops
          docker compose -f compose.prod.yml down
          docker compose --profile server-5 -f compose.prod.yml up -d --build
  
  deploy-server-4:
      runs-on: [self-hosted, server-4]
      needs: test
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
          cd ops
          docker compose -f compose.prod.yml down
          docker compose --profile server-4 -f compose.prod.yml up -d --build

    